name: 'Dart/Flutter Package Analyzer'
description: 'Computes the Pub score of your Dart/Flutter package and posts a detailed commit comment'
author: 'axel-op'
branding:
  color: 'blue'
  icon: 'feather'
inputs: 
  githubToken:
    description: 'Token to connect to Github. Use secrets.GITHUB_TOKEN'
    required: true
  eventPayload:
    description: 'Use toJson(github.event)'
    required: true
  commitSha:
    description: 'Use github.sha'
    required: true
  maxScoreToComment:
    description: 'No comment will be posted if both scores are over this max'
    required: false
    default: 100.0
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --github_token
    - ${{ inputs.githubToken }}
    - --event_payload
    - ${{ inputs.eventPayload }}
    - --commit_sha
    - ${{ inputs.commitSha }}
    - --max_score
    - ${{ inputs.maxScoreToComment }}
