name: 'Dart/Flutter Package Analyzer'
description: 'Computes the Pub score of your Dart/Flutter package and posts a detailed commit comment'
author: 'axel-op'
branding:
  color: 'blue'
  icon: 'feather'
inputs: 
  githubToken:
    description: 'Token to connect to Github. Use secrets.GITHUB_TOKEN'
    required: true
  maxScoreToComment:
    description: 'No comment will be posted if both scores are over this max'
    required: false
    default: 100.0
  relativePath:
    description: 'Path of your package in your repository'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
