name: app
description: A sample command-line application.
author: axel-op <49279289+axel-op@users.noreply.github.com>
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.2
  meta: ^1.1.7
  path: ^1.6.4
  github:
    git:
      url: https://github.com/axel-op/github.dart.git
      ref: f926daab7eda774cf1fb5e2bb1d85deb26af03f6

dev_dependencies:
  pedantic: ^1.8.0
  extra_pedantic: any
