name: Docker image update

on:
  push:
    branches:
      - 'stable'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and push Docker image
        env:
          IMAGE: axelop/dart_package_analyzer
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          EVENT: ${{ github.event_name }}
          GIT_FLUTTER: git://github.com/flutter/flutter.git
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          FLUTTER_SHA=$(git ls-remote $GIT_FLUTTER refs/heads/stable | cut -f 1)
          echo $FLUTTER_SHA is the last commit in the stable branch of Flutter
          echo $DOCKER_TOKEN | sudo docker login --username=axelop --password-stdin
          if [ $EVENT != push ] && sudo docker manifest inspect $IMAGE:$FLUTTER_SHA > /dev/null; then echo No new stable version of Flutter; exit 0; fi
          sudo docker build --squash -f Dockerfile-parent -t $IMAGE:$FLUTTER_SHA .
          sudo docker push $IMAGE:$FLUTTER_SHA
          sudo docker tag $IMAGE:$FLUTTER_SHA $IMAGE:latest
          sudo docker push $IMAGE:latest
