name: Docker image update

on:
  push:
    branches:
      - 'stable'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and push Docker image
        env:
          IMAGE: axelop/dart_package_analyzer
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          EVENT: ${{ github.event_name }}
          GIT_FLUTTER: git://github.com/flutter/flutter.git
          API_ADDRESS: https://registry-1.docker.io/v2
        run: |
          FLUTTER_SHA=$(git ls-remote $GIT_FLUTTER refs/heads/stable | cut -f 1)
          echo $DOCKER_TOKEN | sudo docker login --username=axelop --password-stdin
          API_TOKEN=$(curl -s "https://auth.docker.io/token?scope=repository:$IMAGE:pull&service=registry.docker.io" | jq -r '.token')
          DIGEST=$(curl -s -H "Authorization: Bearer $API_TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "$API_ADDRESS/$IMAGE/manifests/latest" | jq -r '.config.digest')
          PREVIOUS_SHA=$(curl -s -L -H "Authorization: Bearer $API_TOKEN" "$API_ADDRESS/$IMAGE/blobs/$DIGEST" | jq -r '.config.Labels.fluttersha')
          echo $FLUTTER_SHA is the latest commit in the stable branch of Flutter
          echo $PREVIOUS_SHA is the latest commit of Flutter on Docker image
          if [ $EVENT != push ] && [ $FLUTTER_SHA == $PREVIOUS_SHA ]; then echo No new stable version of Flutter; exit 0; fi
          sudo docker build --label "fluttersha=$FLUTTER_SHA" -f Dockerfile-parent -t $IMAGE .
          sudo docker push $IMAGE
