name: Docker image update

on:
  push:
    branches:
      - 'stable'
      - 'master' # TODO remove
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and push Docker image
        run: |
          sudo apt-get update
          sudo apt-get -y remove moby-engine moby-cli
          sudo apt-get -y install docker.io
          FLUTTER_SHA=$(git ls-remote git://github.com/flutter/flutter.git refs/heads/stable | cut -f 1)
          echo $FLUTTER_SHA is the last commit in the stable branch of Flutter
          echo ${{ secrets.DOCKER_TOKEN }} | sudo docker login --username=axelop --password-stdin
          IMAGE=axelop/dart_package_analyzer
          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE:$FLUTTER_SHA > /dev/null; then echo No new stable version of Flutter; exit 0; fi
          sudo docker build -f Dockerfile-parent -t $IMAGE:$FLUTTER_SHA .
          sudo docker push $IMAGE:$FLUTTER_SHA
          sudo docker tag $IMAGE:$FLUTTER_SHA $IMAGE:latest
          sudo docker push $IMAGE:latest
