name: PR comment on stable

on:
  pull_request:
    branches:
      - 'stable'

jobs:

  auto-close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Ask to edit base branch of PR on stable
        uses: superbrothers/auto-close-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: Pull requests on stable branch are not accepted. Please edit the base branch of this pull request. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request.
