name: CI

on:
  push:
    branches: 
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: axel-op/dart_package_analyzer@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        eventPayload: ${{ toJson(github.event) }}
        commitSha: ${{ github.sha }}
        relativePath: 'test_package'
