# This workflow is for internal testing only, and its execution is slower than in regular conditions.
# Please follow the README's instructions to use this action in your project. 

name: Test

on:
  push:
    branches: 
    - '*'

jobs:

  tests:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.5
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      run: |
        apt-get update
        apt-get -y install unzip
        git clone -b stable --depth 1 https://github.com/flutter/flutter.git /flutter
        /flutter/bin/flutter --version
    - name: Compile
      run: |
        cd app
        pub get
        dart2aot bin/main.dart /main.dart.aot
    - name: Path 1
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_RELATIVEPATH: 'test_package'
        INPUT_MINANNOTATIONLEVEL: info
        TESTING: true
      run: dartaotruntime /main.dart.aot
    - name: Path 2
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_RELATIVEPATH: '/test_package'
        INPUT_MINANNOTATIONLEVEL: info
        TESTING: true
      run: dartaotruntime /main.dart.aot
    - name: Path 3
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_RELATIVEPATH: './test_package'
        INPUT_MINANNOTATIONLEVEL: info
        TESTING: true
      run: dartaotruntime /main.dart.aot
    - name: With exception
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_MINANNOTATIONLEVEL: info
        TESTING: true
      run: dartaotruntime /main.dart.aot
    - name: Empty path
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_MINANNOTATIONLEVEL: info
        TESTING: true
      run: |
        cd $GITHUB_WORKSPACE
        mv test_package /test_package
        rm -r *
        mv /test_package/* .
        dartaotruntime /main.dart.aot