# This workflow is for internal testing only. Please follow the README's instructions to use this action in your project. 

name: Test

on:
  push:
    branches: 
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      run: |
        apt-get update
        apt-get -y install unzip
        git clone -b stable --depth 1 https://github.com/flutter/flutter.git /flutter
        /flutter/bin/flutter --version
    - name: Test
      env:
        INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_RELATIVEPATH: 'test_package'
      run: |
        cd app
        pub get
        dart2aot bin/main.dart /main.dart.aot
        dartaotruntime /main.dart.aot
