# This workflow is for internal testing only, and its execution is slower than in regular conditions.
# Please follow the README's instructions to use this action in your project. 

name: Test

on:
  push:
    branches: 
    - '*'

jobs:

  tests:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.6

    env:
      INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_TESTING: true
      INPUT_MINANNOTATIONLEVEL: info
    
    steps:
    - uses: actions/checkout@v1
    - name: Edit path
      run: |
        echo "::add-path::/flutter/bin"
        echo "::add-path::/flutter/bin/cache/dart-sdk/bin"
    - name: Install Flutter
      run: |
        apt-get update
        apt-get -y install unzip
        git clone -b stable --depth 1 https://github.com/flutter/flutter.git /flutter
        flutter --version
    - name: Get dependencies
      run: cd app && pub get
    - name: Path 1
      env:
        INPUT_RELATIVEPATH: test_package
      run: dart /app/bin/main.dart
    - name: Path 2
      env:
        INPUT_RELATIVEPATH: /test_package
      run: dart /app/bin/main.dart
    - name: Path 3
      env:
        INPUT_RELATIVEPATH: ./test_package
      run: dart /app/bin/main.dart
    - name: With exception
      run: dart /app/bin/main.dart
    - name: Empty path
      run: |
        cd $GITHUB_WORKSPACE
        mv test_package /test_package
        rm -r *
        mv /test_package/* .
        dart /app/bin/main.dart
