# Follow the README instructions to use this action in your repository.

name: Test

on:
  push:
    branches-ignore:
      - "stable"
  pull_request:
    branches:
      - "*"

env:
  IMAGE: axelop/dart_package_analyzer:test

jobs:
  test-outputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run tests
        id: steptest
        uses: ./
        with:
          testing: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Test outputs
        run: |
          MAINT=${{ steps.steptest.outputs.maintenance }}
          HEALTH=${{ steps.steptest.outputs.health }}
          echo $MAINT
          echo $HEALTH
          if [[ -z $MAINT ]] || [[ -z $HEALTH ]]; then exit 1; fi
          if (( $(echo "$MAINT < 100" | bc) )) || (( $(echo "$HEALTH < 100" | bc) )); then
            echo Those scores are not perfect
          fi

  test-with-paths:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path: ["test", "/test", "./test"]

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run tests
        uses: ./
        with:
          testing: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ matrix.path }}

  test-pubspec-error:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: rm ${GITHUB_WORKSPACE}/test/pubspec.yaml
      - name: Run tests
        uses: ./
        with:
          testing: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: test
